name: Staging

on:
  pull_request:

  # allow triggering workflow manually.
  workflow_dispatch:

jobs:
  deploy:
    name: Build and copy to staging VPS
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ditatompel'
    environment: staging
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.134.1"
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify --gc --enableGitInfo --cleanDestinationDir

      # - name: Deploy to staging
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --quiet --delete
      #     path: public/
      #     remote_path: ${{ secrets.DEPLOY_PATH }}
      #     remote_host: ${{ secrets.DEPLOY_HOST }}
      #     remote_user: ${{ secrets.DEPLOY_USER }}
      #     remote_key: ${{ secrets.DEPLOY_KEY }}
